services:
  backend:
    build: ./backend
    container_name: backend
    environment:
      - PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:5000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
